# Generated by Django 5.1.2 on 2024-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
    ]
