# Generated by Django 5.1.2 on 2024-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
