# Generated by Django 5.1.2 on 2024-11-12 02:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_privatemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateMessage',
            new_name='PrivateChatGroupMessage',
        ),
        migrations.RenameModel(
            old_name='PrivateChatRoom',
            new_name='PrivateChatGroups',
        ),
    ]
