# Generated by Django 5.1.2 on 2024-11-12 02:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_rename_privatemessage_privatechatgroupmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateChatGroups',
            new_name='PrivateChatRoom',
        ),
        migrations.RenameModel(
            old_name='PrivateChatGroupMessage',
            new_name='PrivateMessage',
        ),
    ]
