# Generated by Django 5.1.2 on 2024-11-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_privatechatgroups_privatechatroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='slug',
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privatechatroom'),
        ),
    ]
