# Generated by Django 5.1.2 on 2024-11-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_publicchatroom_users_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchatroom',
            name='users_online',
        ),
    ]
